server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loacompass
    username: bit1234
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: local

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.finalteam.loacompass.entity

lostark:
  api:
    base-url: https://developer-lostark.game.onstove.com
    key: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IktYMk40TkRDSTJ5NTA5NWpjTWk5TllqY2lyZyIsImtpZCI6IktYMk40TkRDSTJ5NTA5NWpjTWk5TllqY2lyZyJ9.eyJpc3MiOiJodHRwczovL2x1ZHkuZ2FtZS5vbnN0b3ZlLmNvbSIsImF1ZCI6Imh0dHBzOi8vbHVkeS5nYW1lLm9uc3RvdmUuY29tL3Jlc291cmNlcyIsImNsaWVudF9pZCI6IjEwMDAwMDAwMDA1NzU0NDQifQ.pofS5FX4i7bYhu6NdKZcyVErtcMRDbe4H0j6Gc6ZJSd1PunzNUto6ePH6u86TcxrYdCpn_6EdUzIvn_ftx3PNCpshc_ACfBOKVXksvvodhXYJIuc9YjxFx1BrjpJ4fNoClxAvu0xmRnjliq0mk0acyv1diS398k0Mtn6Z1vOVZ8NuLsefJj3SN6b-2q9zxU5-rbLH0g0C4y50mFzI8KIp3oSTxon9Rdet3J1EsID533VXuJgVIONsyzl-x8iB2IBYFIZ20-yZowt5hJi_91ymP4BRQhUFGt9hv3tVfZV6LT4Oh-7VG0iaWzEvVetNAgxndPIkYK5fFDMJ-Zqj4pnMw
