server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loacompass
    username: bit1234
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    config:
      import: application-local.yml

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.finalteam.loacompass.entity

lostark:
  api:
    base-url: https://api-lostark.game.onstove.com
    key: dummy-key # <- 가짜 키