spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loacompass
    username: bit1234
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

discord:
  redirect-uri: https://lochimban.com/discord/callback
