server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loacompass
    username: bit1234
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update  # 또는 create, validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    allow-circular-references: true
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.finalteam.loacompass.entity



# JWT 설정
jwt:
  secret: finalteam_loacompass_secret_key_very_long_at_least_256_bits_please_change_in_production
  expiration: 1800000  # 30분 (밀리초 단위)

# 로깅 설정
logging:
  level:
    org.springframework.security: DEBUG
