server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loacompass
    username: bit1234
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update  # 또는 create, validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.finalteam.loacompass.entity

lostark:
  api:
    base-url: https://developer-lostark.game.onstove.com
    key: ${LOSTARK_API_KEY}

discord:
  client-id: ${DISCORD_CLIENT_ID}
  client-secret: ${DISCORD_CLIENT_SECRET}
  redirect-uri: ${DISCORD_REDIRECT_URI}
