server:
  port: 8080

spring:
  profiles:
    active: local
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/loacompass
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.finalteam.loacompass.entity

lostark:
  api:
    base-url: https://developer-lostark.game.onstove.com
    key: ${LOSTARK_API_KEY}

discord:
  client-id: ${DISCORD_CLIENT_ID}
  client-secret: ${DISCORD_CLIENT_SECRET}
  redirect-uri: ${DISCORD_REDIRECT_URI}

jwt:
  secret: finalteam_loacompass_secret_key_very_long_at_least_256_bits_please_change_in_production
  expiration: 1800000

logging:
  level:
    org.springframework.security: DEBUG
